### ISSUE TITLE
Web content not visible in portlet's config

### ISSUE THREAD

**Issue by Jonohall101** [rotterdam-cs/liferayImageSlider-portlet#1]
Hi guys, I have done most of the set up for the slider and am trying to add the test web content displays I created. However, when I go to the portlet to add the WCDs as slides, the dropdown menu is empty. Help please?!
![slider1](https://cloud.githubusercontent.com/assets/11088871/6442917/54845062-c0eb-11e4-9231-ee376fa47345.png)
![slider2](https://cloud.githubusercontent.com/assets/11088871/6442954/8fab7ddc-c0eb-11e4-861d-63637ebeb2d9.png)

**Comment by alvartaco** [comment]
Hi, 
Please follow the configuration document from "Configure RCS Slider's Web Contents".
Have in mind that Liferay 6.2 has an issue, be careful of not create from scratch the webcontent using the required structure and template.
Create them with a normal structure, then re-open them, change to the slider's structure, publish it and verify the structure is applied.

See: 
"1.Log in as an admin user and in the Dock Bar go to Admin → Site Administration → Content.
Fig 14: Content Menu
2.Click on Web Content → Add → Basic Web Content.
Yes, you first need to create a Basic Web Content, save it, and then update this one to use the SLIDER_STRUCTURE created in previous steps, this is because Liferay has an issue related to Structures saved first time."

Please let me know if this procedure fixed your issue.
KR
Alejandro

**Comment by Jonohall101** [comment]
Hi Alejandro, 
I used the guide throughout the installation and set-up, including creating a Basic content display and then editing it to bypass the 6.2 bug. 
Any ideas?
Many thanks for your help,
Jon

**Comment by alvartaco** [comment]
Hi, this is important, and needed to have the plugin running:

"4. Fill Name and Description fields with *required “SLIDER_STRUCTURE” value.
Fig 6: Structure Name and Description, required values."

Name and description must be "SLIDER_STRUCTURE".

I was able, accidentally, to reproduce your issue, and saw the log file: 
[SliderArticleUtil:118] Can not get ddmStructureKey.

That gave me the clue...

Please apply the change to the sructure's Description field and let me know.

BR
Alejandro

**Comment by Jonohall101** [comment]
Ah I see. Rookie mistake. I have changed this and there is some development but not fixed. If I create a new Web content display for use in the slider, and then go to the slider's configuration menu, the the Web Content dropdown menu is populating with blank fields, like it recognises something is being added but can't display it. Thoughts?
KR 
Jon
![slider3](https://cloud.githubusercontent.com/assets/11088871/6444287/87ad63f8-c0f4-11e4-815f-5afb9bd02eaa.png)

**Comment by Jonohall101** [comment]
Sorry. #...create a new BASIC content display for use ...

**Comment by alvartaco** [comment]
Umhhh...
It looks related to some css you have applied, some theme related issue.
Can you try using the liferay default theme in the page the Slider is being used?
And... if that is not the case, try to remove the Slider plugin from the page, the add it again.
Let's see.
Ale

**Comment by Jonohall101** [comment]
I have reset the theme to the Liferay default theme but issue persists. I will remove the plugin and go through the process again tomorrow morning.

**Comment by alvartaco** [comment]
Hi, try this...

Add to the portlet Look and Feel advanced styles the select's color to black:

.aui select {
    color: black;
}

![screenshot from 2015-03-02 13 58 36](https://cloud.githubusercontent.com/assets/1532724/6445693/85fbf17e-c0e4-11e4-8199-3d1478edbf18.png)
![screenshot from 2015-03-02 14 01 11](https://cloud.githubusercontent.com/assets/1532724/6445738/d077dbfa-c0e4-11e4-88c5-45157ec3f933.png)
